baseURL = ""
languageCode = "en-us"
title = "Welcome To Metricly"
theme = "metricly"
staticDir = ["static", "blog-page/dist"]
[taxonomies]
  author = "author"
  category = "category"
  tag = "tags"
metaDataFormat = "yaml"
